use_frameworks!

platform :ios, '8.0'

target 'DRStaticRequestManager_Example' do
  pod 'DRStaticRequestManager', :path => '../'

  target 'DRStaticRequestManager_Tests' do
    inherit! :search_paths

    
  end
end
